#!/usr/bin/env bash

set -e
set -x

# Change to this script's own directory, then back up one level.
cd "$(dirname "$0")"
cd ..

if [ ! -f wander_server.crt ]; then
  pushd ~/.ssh

  # All of this makes a self-signed certificate. You know what's hard to get modern browsers to use? A self-signed certificate.
  # See https://gist.github.com/tadast/9932075
  openssl genrsa -out wander_server.orig.key 4096
  openssl rsa -in wander_server.orig.key -out wander_server.key
  openssl req -new -key wander_server.key -x509 -nodes -new -out wander_server.crt -subj /CN=localhost.ssl -reqexts SAN -extensions SAN -config <(cat /System/Library/OpenSSL/openssl.cnf <(printf '[SAN]\nsubjectAltName=DNS:localhost.ssl')) -sha256 -days 3650
  grep localhost.ssl /private/etc/hosts || (echo "127.0.0.1 localhost.ssl" | sudo tee -a /private/etc/hosts)

  popd
  cp ~/.ssh/wander_server.* .
fi

# Thin doesn't seem to support HTTP and HTTPS on the same port (fair), but *does* support HTTPS and WSS on the same port.
bundle exec thin start -R config.ru -p 3001 --ssl --ssl-disable-verify --ssl-key-file ./wander_server.key --ssl-cert-file ./wander_server.crt

# Sometimes you want to run your server with "rerun" - that makes it easy to restart your production game by updating an empty file called "restart.txt". If you do, make sure to
# put "rerun" in your Gemfile.
#bundle exec rerun --dir tmp --pattern restart.txt "thin start -R config.ru -p 3001 --ssl --ssl-disable-verify --ssl-key-file ./wander_server.key --ssl-cert-file ./wander_server.crt"
