#!/usr/bin/env ruby

require "trollop"

opts = Trollop::options do
  banner <<BANNER
Create a new Pixiurge game or application. This will create a
directory hierarchy under the current directory.

Usage: pixiurge [options] my_game_name

Where [options] can be empty, or:
BANNER
end

if ARGV.size != 1
  Trollop::die "You must supply exactly one name for your game or application, neither more nor less. Run trollop --help if you need more usage information."
end

require File.expand_path('lib/pixiurge/commands/generator', Dir.pwd)
Pixiurge::Commands::Generator.start
