#!/usr/bin/env ruby

require "trollop"

opts = Trollop::options do
  banner <<BANNER
Create a new Pixiurge game or application. This will create a
directory hierarchy under the current directory.

Usage: pixiurge [options] my_game_name

Where [options] can be empty, or:
BANNER
end

begin
  require 'pixiurge/commands/generator'
rescue LoadError
  require File.expand_path('lib/pixiurge/commands/generator', __dir__ + "/..")
end

Pixiurge::Commands::Generator.start
